apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: external-secrets
  namespace: default
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-secrets
    directory: {}
    path: ""
    repoURL: https://charts.external-secrets.io
    skipCrds: false
    targetRevision: 0.18.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
