apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: flink-operator
  namespace: argocd
spec:
  destination:
    namespace: flink-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: flink-operator
    directory: {}
    helm: https://downloads.apache.org/flink/flink-kubernetes-operator-1.12.1/
    path: ""
    repoURL: git@github.com:bytetum/k8s-dataplatform-quickstart.git
    skipCrds: false
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
