apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: polaris-setup
  namespace: argocd
spec:
  destination:
    namespace: polaris-setup
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops/manifests/polaris-setup
    repoURL: git@github.com:bytetum/k8s-dataplatform-quickstart.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
