apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: secrets
  namespace: argocd
spec:
  destination:
    namespace: secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops/manifests/secrets
    repoURL: git@ssh-source.netcompany.com:22/tfs/Netcompany/AOJHECOM/_git/essence
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
