apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: warpstream-agent
  namespace: argocd
spec:
  destination:
    namespace: warpstream-poc
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: warpstream-agent
    directory: {}
    path: ""
    repoURL: https://warpstreamlabs.github.io/charts
    skipCrds: false
    targetRevision: 0.15.28
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
