apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: marquez-postgres-credentials
  namespace: lakehouse-marquez
spec:
  dataFrom:
  - extract:
      key: marquez-database-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: marquez-postgres-credentials
    template:
      data:
        password: '{{ .password }}'
        postgres-password: '{{ .password }}'
        replication-password: '{{ .password }}'
