apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-metadata-secret
  namespace: lakehouse-openmetadata
spec:
  dataFrom:
  - extract:
      key: openmetadata-airflow-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: airflow-metadata-secret
    template:
      data:
        connection: '{{ .connection }}'
