apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secrets
  namespace: lakehouse-openmetadata
spec:
  dataFrom:
  - extract:
      key: openmetadata-database-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: mysql-secrets
    template:
      data:
        mysql-password: '{{ .password }}'
        mysql-root-password: '{{ index . "root-password" }}'
        openmetadata-mysql-password: '{{ .password }}'
