apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-secrets
  namespace: lakehouse-openmetadata
spec:
  dataFrom:
  - extract:
      key: openmetadata-airflow-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: airflow-secrets
    template:
      data:
        AIRFLOW_ADMIN_PASSWORD: '{{ .password }}'
        openmetadata-airflow-password: '{{ .password }}'
