apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flink-bucket-credentials
  namespace: flink-kubernetes-operator
spec:
  dataFrom:
  - extract:
      key: flink-bucket-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: flink-bucket-credentials
