apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-m3-test
  name: postgres-m3-test
  namespace: lakehouse-kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-m3-test
  template:
    metadata:
      labels:
        app: postgres-m3-test
    spec:
      containers:
      - args:
        - postgres
        - -c
        - wal_level=logical
        - -c
        - max_replication_slots=4
        - -c
        - max_wal_senders=4
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: dbname
              name: pricefiles-db-credentials
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: pricefiles-db-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pricefiles-db-credentials
        image: postgres:14.18-bookworm
        name: postgres
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
        - mountPath: /docker-entrypoint-initdb.d
          name: postgres-init
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-m3-test-data
      - configMap:
          name: postgres-m3-test-init
        name: postgres-init
