apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: polaris-root-password
  namespace: lakehouse-kafka-connect
spec:
  dataFrom:
  - extract:
      key: polaris-root-password
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: polaris-root-password
