apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: schema-registry-credentials
  namespace: lakehouse-kafka-connect
spec:
  dataFrom:
  - extract:
      key: schema-registry-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: schema-registry-credentials
