apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-m3-test-data
  namespace: lakehouse-kafka-connect
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
