apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warpstream-bucket-credentials
  namespace: warpstream
spec:
  dataFrom:
  - extract:
      key: id:827b85c8-babe-4a43-8af2-dce1dd530081
      version: latest_enabled
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: warpstream-bucket-credentials
