apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warpstream-agent-apikey
  namespace: warpstream
spec:
  dataFrom:
  - extract:
      key: id:ae402e70-87ee-435a-8ecc-f6c91c57ae9c
      version: latest_enabled
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: warpstream-agent-apikey
