apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: polaris
spec:
  dataFrom:
  - extract:
      key: id:842cb98e-9786-4cc6-9af7-424f9278d808
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: postgres-secret
