apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-secret
  namespace: polaris
spec:
  dataFrom:
  - extract:
      key: aws-secret-local
      version: latest_enabled
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: aws-secret-local
