apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: polaris-postgres-credentials
  namespace: polaris
spec:
  dataFrom:
  - extract:
      key: polaris-postgres-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: polaris-postgres-credentials
