apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # A clear, descriptive name for your application in the Argo CD UI.
  name: redis-helm-deployment
  # This should be the namespace where Argo CD is running.
  namespace: argocd
spec:
  # The Argo CD project this application will belong to. 'default' is standard.
  project: default

  # This section defines the source of the application, which is a Helm chart.
  source:
    # The URL of the repository where the Helm chart is located.
    repoURL: 'https://charts.bitnami.com/bitnami'
    # The name of the chart within the repository.
    chart: redis
    # It's a best practice to pin the chart version for predictable deployments.
    targetRevision: 18.18.0

  # This section defines where the resources will be deployed.
  destination:
    # This special URL means "deploy to the same Kubernetes cluster where Argo CD is running".
    server: 'https://kubernetes.default.svc'
    # The Kubernetes namespace to deploy Redis into.
    namespace: redis

  # This policy controls how the application stays synchronized.
  syncPolicy:
    automated:
      # If 'true', Argo CD will delete resources that are removed from the Helm chart.
      prune: true
      # If 'true', Argo CD will automatically fix any manual changes made to the deployment.
      selfHeal: true
    syncOptions:
    # This is a very useful option that tells Argo CD to create the 'redis'
    # namespace if it doesn't already exist.
    - CreateNamespace=true