apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iceberg-bucket-credentials
  namespace: trino
spec:
  dataFrom:
  - extract:
      key: iceberg-bucket-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: iceberg-bucket-credentials
