apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warpstream-schema-registry-secrets
  namespace: warpstream
spec:
  dataFrom:
  - extract:
      key: warpstream-schema-registry-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: warpstream-schema-registry-secrets
