apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres-deployment
  namespace: lakehouse-polaris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: kind_local
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: polaris-postgres-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: polaris-postgres-credentials
        image: postgres:14.18-bookworm
        name: postgres-container
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: polaris-postgres-data
