apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: polaris-key-pair
  namespace: lakehouse-polaris
spec:
  dataFrom:
  - extract:
      key: polaris-key-pair
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: polaris-key-pair
