apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: polaris-postgres-credentials
  namespace: lakehouse-polaris
spec:
  dataFrom:
  - extract:
      key: polaris-postgres-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: polaris-postgres-credentials
    template:
      data:
        jdbcUrl: jdbc:postgresql://postgres-service:5432/kind_local
        password: '{{ .password }}'
        username: '{{ .username }}'
