apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: pulumi
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.18.2
    helm.sh/chart: cert-manager-v1.18.2
  name: cert-manager
  namespace: ns-cert-manager
