apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: local-kubernetes-secret-store
spec:
  conditions:
  - namespaces:
    - kafka-connect
    - polaris
    - trino
    - warpstream
    - flink-kubernetes-operator
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: local-secret-store-reader
          namespace: local-secrets
      remoteNamespace: local-secrets
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: local-secrets
          type: ConfigMap
