apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  namespace: external-secrets
spec:
  provider:
    fake:
      data:
      - key: 'id: c2f85be8-7fd0-402d-8229-6de987bcbbb4'
        value: '{"SCALEWAY_ACCESS_KEY": "ACCESS_KEY", "SCALEWAY_SECRET_KEY": "SECRET_KEY"}'
