apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  namespace: external-secrets
spec:
  provider:
    fake:
      data:
      - key: aws-secret-local
        value: "a-placeholder-value"
        valueMap:
          access_key_id: test
          secret_access_key: test
