apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  namespace: external-secrets
spec:
  provider:
    fake:
      data:
      - key: bucket/access-key
        value: local-app-user
      - key: bucket/secret-key
        value: a-very-secure-password
