apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: basic-checkpoint-ha-sql-example
  namespace: flink-kubernetes-operator
spec:
  flinkConfiguration:
    env.java.opts: -verbose:gc -XX:+PrintGCDetails
    jobmanager.scheduler: adaptive
    kafka.bootstrap.servers: warpstream-agent.default.svc.cluster.local:9092
    kafka.input.topic: input-topic
    kafka.output.topic: output-topic
    taskmanager.numberOfTaskSlots: "2"
  flinkVersion: v1_20
  image: flink:1.20
  job:
    args:
    - -i
    - -e
    - "-- This script is a template. Values are injected by Flink's configuration.\r\n\r\nCREATE
      TABLE input_source (\r\n    `message` STRING\r\n) WITH (\r\n    'connector'
      = 'kafka',\r\n    'topic' = '${kafka.input.topic}',\r\n    'properties.bootstrap.servers'
      = '${kafka.bootstrap.servers}',\r\n    'scan.startup.mode' = 'latest-offset',\r\n
      \   'format' = 'raw',\r\n    'properties.security.protocol' = 'SASL_PLAINTEXT',\r\n
      \   'properties.sasl.mechanism' = 'PLAIN',\r\n    'properties.sasl.jaas.config'
      = '${kafka.sasl.jaas.config}'\r\n);\r\n\r\nCREATE TABLE output_sink (\r\n    `message`
      STRING\r\n) WITH (\r\n    'connector' = 'kafka',\r\n    'topic' = '${kafka.output.topic}',\r\n
      \   'properties.bootstrap.servers' = '${kafka.bootstrap.servers}',\r\n    'format'
      = 'raw',\r\n    'properties.security.protocol' = 'SASL_PLAINTEXT',\r\n    'properties.sasl.mechanism'
      = 'PLAIN',\r\n    'properties.sasl.jaas.config' = '${kafka.sasl.jaas.config}'\r\n);\r\n\r\nINSERT
      INTO output_sink\r\nSELECT\r\n    'PROCESSED VIA CONFIGMAP: ' || UPPER(`message`)\r\nFROM\r\n
      \   input_source;"
    entryClass: org.apache.flink.table.client.SqlClient
    jarURI: https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-client/1.17.1/flink-sql-client-1.17.1.jar
    parallelism: 1
    upgradeMode: stateless
  jobManager:
    resource:
      cpu: 1
      memory: 2048m
  podTemplate:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: flink-warpstream-credentials-secret
        name: flink-main-container
  service:
    port: 8081
    targetPort: 8081
    type: ClusterIP
  serviceAccount: flink
  taskManager:
    resource:
      cpu: 1
      memory: 2048m
