apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-impersonate-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-impersonate
subjects:
- kind: ServiceAccount
  name: flink-operator
  namespace: flink-kubernetes-operator
