apiVersion: v1
data:
  job.sql: "-- This script is a template. Values are injected by Flink's configuration.\r\n\r\nCREATE
    TABLE input_source (\r\n    `message` STRING\r\n) WITH (\r\n    'connector' =
    'kafka',\r\n    'topic' = '${kafka.input.topic}',\r\n    'properties.bootstrap.servers'
    = '${kafka.bootstrap.servers}',\r\n    'scan.startup.mode' = 'latest-offset',\r\n
    \   'format' = 'raw',\r\n    'properties.security.protocol' = 'SASL_PLAINTEXT',\r\n
    \   'properties.sasl.mechanism' = 'PLAIN',\r\n    'properties.sasl.jaas.config'
    = '${kafka.sasl.jaas.config}'\r\n);\r\n\r\nCREATE TABLE output_sink (\r\n    `message`
    STRING\r\n) WITH (\r\n    'connector' = 'kafka',\r\n    'topic' = '${kafka.output.topic}',\r\n
    \   'properties.bootstrap.servers' = '${kafka.bootstrap.servers}',\r\n    'format'
    = 'raw',\r\n    'properties.security.protocol' = 'SASL_PLAINTEXT',\r\n    'properties.sasl.mechanism'
    = 'PLAIN',\r\n    'properties.sasl.jaas.config' = '${kafka.sasl.jaas.config}'\r\n);\r\n\r\nINSERT
    INTO output_sink\r\nSELECT\r\n    'PROCESSED VIA CONFIGMAP: ' || UPPER(`message`)\r\nFROM\r\n
    \   input_source;"
kind: ConfigMap
metadata:
  name: flink-sql-script
  namespace: flink-kubernetes-operator
