apiVersion: v1
data:
  job.sql: "CREATE TABLE readings (\r\n  sensorId STRING,\r\n  reading DOUBLE,\r\n
    \ eventTime_ltz AS TO_TIMESTAMP_LTZ(`timestamp`, 3),\r\n  `ts` TIMESTAMP(3) METADATA
    FROM 'timestamp',\r\n  `timestamp` BIGINT,\r\n    WATERMARK FOR eventTime_ltz
    AS eventTime_ltz - INTERVAL '30' SECONDS\r\n) WITH (\r\n  'connector' = 'kafka',\r\n
    \ 'topic' = 'sensor.readings',\r\n  'properties.bootstrap.servers' = 'kafka:29092',\r\n
    \ 'properties.group.id' = 'group.sensor.readings',\r\n  'format' = 'json',\r\n
    \ 'scan.startup.mode' = 'earliest-offset',\r\n  'json.timestamp-format.standard'
    = 'ISO-8601',\r\n  'json.fail-on-missing-field' = 'false',\r\n  'json.ignore-parse-errors'
    = 'true'\r\n);"
kind: ConfigMap
metadata:
  name: flink-sql-script
  namespace: flink-kubernetes-operator
