apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway-service
  namespace: flink-kubernetes-operator
spec:
  ports:
  - name: hiveserver2
    port: 10000
    targetPort: 10000
  selector:
    app: basic-checkpoint-ha-sql-example
    component: jobmanager
  type: ClusterIP
