apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: kafka-connect
  namespace: argocd
spec:
  destination:
    namespace: lakehouse-kafka-connect
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: values.yaml
      recurse: true
    path: gitops/environments/kind/manifests/applications/kafka-connect
    repoURL: https://github.com/bytetum/k8s-dataplatform-quickstart.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
