apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: silver-m3-debug-customer-order-analytics
  namespace: argocd
spec:
  destination:
    namespace: lakehouse-flink
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: values.yaml
      recurse: true
    path: gitops/environments/kind/manifests/applications/silver-m3-debug-customer-order-analytics
    repoURL: https://github.com/bytetum/k8s-dataplatform-quickstart.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
