apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trino-polaris-credentials
  namespace: lakehouse-trino
spec:
  dataFrom:
  - extract:
      key: polaris-root-password
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: trino-polaris-credentials
