apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/managed-by: pulumi
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: 1.12.1
    helm.sh/chart: flink-kubernetes-operator-1.12.1
  name: flink-role-binding
  namespace: ns-flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink
subjects:
- kind: ServiceAccount
  name: flink
  namespace: ns-flink
