apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/managed-by: pulumi
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: 1.12.1
    helm.sh/chart: flink-kubernetes-operator-1.12.1
  name: flink
  namespace: ns-flink
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
