apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: 1.12.1
    helm.sh/chart: flink-kubernetes-operator-1.12.1
  name: flink-operator
  namespace: ns-flink
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - flink.apache.org
  resources:
  - flinkdeployments
  - flinkdeployments/finalizers
  - flinksessionjobs
  - flinksessionjobs/finalizers
  - flinkstatesnapshots
  - flinkstatesnapshots/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - flink.apache.org
  resources:
  - flinkdeployments/status
  - flinksessionjobs/status
  - flinkstatesnapshots/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
