config:
  Infrastructure:kube_context: kind-dataplatform-mac
  Infrastructure:repo_url: https://github.com/bytetum/k8s-dataplatform-quickstart.git
  Infrastructure:target_revision: mac-local
  Infrastructure:manifests_path: gitops/environments/mac/manifests/argocd
encryptionsalt: v1:we7WqBwK6nw=:v1:E5o0eg+CpSdkMG1e:Whb0AiYSpPyFslU08mDFNczWrEjiiQ==
