apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warpstream-bucket-credentials
  namespace: lakehouse-warpstream
spec:
  dataFrom:
  - extract:
      key: warpstream-bucket-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes-secret-store
  target:
    creationPolicy: Owner
    name: warpstream-bucket-credentials
