apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: container-registry-read-credentials
  namespace: kafka-connect
spec:
  dataFrom:
  - extract:
      key: id:1cf21d4a-b561-4353-9981-fecafe592689
      version: latest_enabled
  secretStoreRef:
    kind: ClusterSecretStore
    name: shared-secret-store
  target:
    creationPolicy: Owner
    name: container-registry-read-credentials
    template:
      data:
        .dockerconfigjson: '{"auths":{"rg.nl-ams.scw.cloud":{"auth":"{{ printf "%s:%s"
          .SCALEWAY_ACCESS_KEY .SCALEWAY_SECRET_KEY | b64enc }}"}}}'
      type: kubernetes.io/dockerconfigjson
