apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pricefiles-db-credentials
  namespace: kafka-connect
spec:
  dataFrom:
  - extract:
      key: id:86fac104-7ff1-47d8-8cd1-7e2d74dbc0fd
      version: latest_enabled
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: pricefiles-db-credentials
