apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iceberg-bucket-credentials
  namespace: kafka-connect
spec:
  dataFrom:
  - extract:
      key: id:c2f85be8-7fd0-402d-8229-6de987bcbbb4
      version: latest_enabled
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    name: iceberg-bucket-credentials
