apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: local-kubernetes-secret-store
spec:
  conditions:
  - namespaces:
    - lakehouse-kafka-connect
    - lakehouse-polaris
    - lakehouse-trino
    - lakehouse-warpstream
    - lakehouse-flink
    - lakehouse-marquez
    - lakehouse-openmetadata
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: local-secret-store-reader
          namespace: lakehouse-secrets
      remoteNamespace: lakehouse-secrets
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: lakehouse-secrets
          type: ConfigMap
